import type {
  IntakeFormData,
  OverviewResult,
  FinancialAidResult,
  SchoolMatchResult,
  ActionPlanResult,
  RoadmapResult,
} from './types';

// Dynamic import to keep bundle lean
async function getJsPDF() {
  const { jsPDF } = await import('jspdf');
  return jsPDF;
}
async function getAutoTable() {
  const mod = await import('jspdf-autotable');
  return mod.default;
}

const TEAL: [number, number, number] = [15, 110, 86];
const AMBER: [number, number, number] = [186, 117, 23];
const DARK: [number, number, number] = [28, 28, 26];
const GRAY: [number, number, number] = [107, 106, 101];
const LIGHT_BG: [number, number, number] = [248, 246, 241];
const WHITE: [number, number, number] = [255, 255, 255];
const GREEN: [number, number, number] = [59, 109, 17];
const CORAL: [number, number, number] = [216, 90, 48];

const PAGE_W = 210;
const MARGIN = 14;
const CONTENT_W = PAGE_W - MARGIN * 2;
const FOOTER_Y = 287;
const HEADER_H = 10;
const FOOTER_H = 10;
const CONTENT_BOTTOM = FOOTER_Y - 2;

const FOOTER_TEXT =
  'Generated by Path Forward  |  Verify all information with your caseworker';

type Doc = InstanceType<Awaited<ReturnType<typeof getJsPDF>>>;

function fmt(n: number): string {
  return n.toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
}

function confidenceLabel(c: string): string {
  if (c === 'certain' || c === 'eligible') return 'Confirmed eligible';
  if (c === 'high' || c === 'likely_eligible') return 'Very likely eligible';
  return 'Needs verification';
}

function confidenceColor(c: string): [number, number, number] {
  if (c === 'certain' || c === 'eligible') return GREEN;
  if (c === 'high' || c === 'likely_eligible') return TEAL;
  return AMBER;
}

function addHeader(doc: Doc, pageNum: number) {
  doc.setFillColor(...TEAL);
  doc.rect(0, 0, PAGE_W, HEADER_H, 'F');
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text('PATH FORWARD  |  Your College Readiness Plan', MARGIN, 6.5);
  doc.setFont('helvetica', 'normal');
  doc.text(`Page ${pageNum}`, PAGE_W - MARGIN, 6.5, { align: 'right' });
}

function addFooter(doc: Doc) {
  doc.setFillColor(...TEAL);
  doc.rect(0, FOOTER_Y - 1, PAGE_W, FOOTER_H + 1, 'F');
  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...WHITE);
  doc.text(FOOTER_TEXT, PAGE_W / 2, FOOTER_Y + 4, { align: 'center' });
}

function sectionHeader(doc: Doc, y: number, title: string): number {
  doc.setFillColor(...TEAL);
  doc.roundedRect(MARGIN, y, CONTENT_W, 9, 2, 2, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text(title, MARGIN + 4, y + 6);
  return y + 13;
}

function notGenerated(doc: Doc, y: number, name: string): number {
  doc.setFillColor(...LIGHT_BG);
  doc.roundedRect(MARGIN, y, CONTENT_W, 16, 2, 2, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...GRAY);
  doc.text(
    `${name}: Generate this section in the app for personalized results.`,
    MARGIN + 6, y + 9.5,
    { maxWidth: CONTENT_W - 10 }
  );
  return y + 20;
}

export async function exportToPDF(
  _intakeData: IntakeFormData,
  overview: OverviewResult | null,
  financial: FinancialAidResult | null,
  schools: SchoolMatchResult | null,
  actionPlan: ActionPlanResult | null,
  roadmap: RoadmapResult | null,
): Promise<void> {
  const JsPDF = await getJsPDF();
  const autoTable = await getAutoTable();
  const doc = new JsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  let pageNum = 1;
  let y = HEADER_H + 6;

  // Helper: start a new page with header/footer scaffold
  function newPage() {
    addFooter(doc);
    doc.addPage();
    pageNum++;
    addHeader(doc, pageNum);
    y = HEADER_H + 6;
  }

  // Helper: ensure there's enough room, otherwise new page
  function need(h: number) {
    if (y + h > CONTENT_BOTTOM) newPage();
  }

  // ── Cover Page ─────────────────────────────────────────────────────────────
  doc.setFillColor(...TEAL);
  doc.rect(0, 0, PAGE_W, 297, 'F');

  // Amber accent
  doc.setFillColor(...AMBER);
  doc.rect(0, 78, PAGE_W, 2.5, 'F');

  // Brand name
  doc.setFontSize(30);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text('PATH FORWARD', PAGE_W / 2, 48, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(180, 230, 215);
  doc.text('Your path to college starts here', PAGE_W / 2, 57, { align: 'center' });

  // Plan title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text('College Readiness Plan', PAGE_W / 2, 94, { align: 'center' });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(180, 230, 215);
  const today = new Date().toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric',
  });
  doc.text(`Generated: ${today}`, PAGE_W / 2, 103, { align: 'center' });
  doc.text('Powered by AI  |  Verified with Arizona Program Data', PAGE_W / 2, 109, { align: 'center' });

  // Sections box
  const sectionsList = [
    overview && '1.  Overview & Readiness Scores',
    financial && '2.  Financial Aid Programs',
    schools && '3.  School Matches',
    actionPlan && '4.  Action Plan',
    roadmap && '5.  Semester Roadmap',
  ].filter(Boolean) as string[];

  if (sectionsList.length > 0) {
    const boxH = sectionsList.length * 9 + 18;
    doc.setFillColor(10, 79, 62);
    doc.roundedRect(MARGIN + 20, 122, CONTENT_W - 40, boxH, 3, 3, 'F');

    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...AMBER);
    doc.text('SECTIONS IN THIS PLAN', PAGE_W / 2, 132, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(200, 240, 225);
    sectionsList.forEach((s, i) => {
      doc.text(s, MARGIN + 30, 141 + i * 9);
    });
  }

  // Privacy note
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(140, 200, 180);
  doc.text(
    'Your data was generated in your browser. No personal data was stored or shared.',
    PAGE_W / 2, 270, { align: 'center', maxWidth: CONTENT_W }
  );
  doc.text(
    'This plan is a navigation guide, not legal or financial advice.',
    PAGE_W / 2, 277, { align: 'center', maxWidth: CONTENT_W }
  );

  addFooter(doc);

  // ── Content pages ──────────────────────────────────────────────────────────
  doc.addPage();
  pageNum++;
  addHeader(doc, pageNum);
  y = HEADER_H + 6;

  // ────────────────────────────────────────────────────────────────────────────
  // SECTION 1: OVERVIEW & READINESS
  // ────────────────────────────────────────────────────────────────────────────
  y = sectionHeader(doc, y, '1.  OVERVIEW & READINESS SCORES');

  if (overview) {
    // Key insight
    if (overview.key_insight) {
      need(18);
      doc.setFillColor(...AMBER);
      doc.roundedRect(MARGIN, y, CONTENT_W, 14, 2, 2, 'F');
      doc.setFontSize(7);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...WHITE);
      doc.text('KEY INSIGHT', MARGIN + 4, y + 5);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      const lines = doc.splitTextToSize(overview.key_insight, CONTENT_W - 10);
      doc.text(lines.slice(0, 2), MARGIN + 4, y + 10.5);
      y += 18;
    }

    // Scores table via autoTable
    need(50);
    const scoreRows = [
      ['Overall Readiness', String(overview.readiness.overall), overview.readiness.overall_summary ?? ''],
      ['Academic', String(overview.readiness.academic.score), overview.readiness.academic.summary ?? ''],
      ['Financial Aid', String(overview.readiness.financial_aid.score), overview.readiness.financial_aid.summary ?? ''],
      ['Application', String(overview.readiness.application.score), overview.readiness.application.summary ?? ''],
      ['Timeline', String(overview.readiness.timeline.score), overview.readiness.timeline.summary ?? ''],
    ];

    autoTable(doc, {
      startY: y,
      head: [['Category', 'Score', 'Summary']],
      body: scoreRows,
      theme: 'grid',
      margin: { left: MARGIN, right: MARGIN },
      headStyles: { fillColor: TEAL, textColor: WHITE, fontStyle: 'bold', fontSize: 8 },
      bodyStyles: { fontSize: 7.5, textColor: DARK },
      columnStyles: {
        0: { cellWidth: 32, fontStyle: 'bold' },
        1: { cellWidth: 16, halign: 'center', fontStyle: 'bold', textColor: TEAL },
        2: { cellWidth: CONTENT_W - 48 },
      },
      didDrawCell: (data) => {
        if (data.column.index === 1 && data.section === 'body') {
          const raw = data.row.raw as string[];
          const score = Number(raw[1]);
          const color: [number, number, number] =
            score >= 75 ? GREEN : score >= 50 ? TEAL : score >= 30 ? AMBER : CORAL;
          data.cell.styles.textColor = color;
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 6;

    // Matched programs overview
    if (overview.matched_programs.length > 0) {
      need(16);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...DARK);
      doc.text('Funding You May Qualify For', MARGIN, y);
      y += 5;

      const progRows = overview.matched_programs.map(p => [
        p.name,
        p.max_amount ?? '—',
        confidenceLabel(p.confidence),
      ]);

      autoTable(doc, {
        startY: y,
        head: [['Program', 'Max Amount', 'Eligibility']],
        body: progRows,
        theme: 'striped',
        margin: { left: MARGIN, right: MARGIN },
        headStyles: { fillColor: [10, 79, 62], textColor: WHITE, fontStyle: 'bold', fontSize: 8 },
        bodyStyles: { fontSize: 7.5, textColor: DARK },
        columnStyles: {
          0: { cellWidth: 80 },
          1: { cellWidth: 36, halign: 'right' },
          2: { cellWidth: CONTENT_W - 116 },
        },
        alternateRowStyles: { fillColor: [245, 243, 238] },
      });
      y = (doc as any).lastAutoTable.finalY + 6;
    }
  } else {
    y = notGenerated(doc, y, 'Overview & Readiness Scores');
  }

  // ────────────────────────────────────────────────────────────────────────────
  // SECTION 2: FINANCIAL AID
  // ────────────────────────────────────────────────────────────────────────────
  need(16);
  y = sectionHeader(doc, y, '2.  FINANCIAL AID PROGRAMS');

  if (financial) {
    const aidRows = financial.matched_programs.map(p => [
      p.name,
      p.max_amount ?? '—',
      confidenceLabel(p.confidence),
      p.deadline ?? 'Rolling',
      p.next_action ?? '—',
    ]);

    autoTable(doc, {
      startY: y,
      head: [['Program', 'Amount', 'Eligibility', 'Deadline', 'Next Action']],
      body: aidRows,
      theme: 'grid',
      margin: { left: MARGIN, right: MARGIN },
      headStyles: { fillColor: TEAL, textColor: WHITE, fontStyle: 'bold', fontSize: 7.5 },
      bodyStyles: { fontSize: 7, textColor: DARK },
      columnStyles: {
        0: { cellWidth: 44, fontStyle: 'bold' },
        1: { cellWidth: 22, halign: 'right' },
        2: { cellWidth: 32 },
        3: { cellWidth: 24 },
        4: { cellWidth: CONTENT_W - 122 },
      },
      alternateRowStyles: { fillColor: [245, 243, 238] },
      didDrawCell: (data) => {
        if (data.column.index === 2 && data.section === 'body') {
          const prog = financial.matched_programs[data.row.index];
          if (prog) {
            data.cell.styles.textColor = confidenceColor(prog.confidence);
          }
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 6;

    // Source URLs
    need(10 + financial.matched_programs.length * 5);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK);
    doc.text('Program Sources:', MARGIN, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...TEAL);
    financial.matched_programs.forEach(p => {
      need(5);
      doc.text(`${p.name}: ${p.source_url}`, MARGIN + 4, y, { maxWidth: CONTENT_W - 6 });
      y += 4.5;
    });
    y += 3;
  } else {
    y = notGenerated(doc, y, 'Financial Aid Programs');
  }

  // ────────────────────────────────────────────────────────────────────────────
  // SECTION 3: SCHOOL MATCHES
  // ────────────────────────────────────────────────────────────────────────────
  need(16);
  y = sectionHeader(doc, y, '3.  SCHOOL MATCHES');

  if (schools) {
    if (schools.other_options_note) {
      need(12);
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(...GRAY);
      doc.text(schools.other_options_note, MARGIN, y, { maxWidth: CONTENT_W });
      y += 8;
    }

    schools.school_matches.forEach((school, idx) => {
      const cb = school.cost_breakdown;
      need(20);

      // School name header
      doc.setFillColor(...LIGHT_BG);
      doc.roundedRect(MARGIN, y, CONTENT_W, 10, 2, 2, 'F');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...DARK);
      doc.text(`${idx + 1}.  ${school.name}`, MARGIN + 4, y + 7);

      const fitColor = school.fit_label === 'Strong match' ? GREEN :
        school.fit_label === 'Good match' ? TEAL : AMBER;
      doc.setFillColor(...fitColor);
      doc.roundedRect(PAGE_W - MARGIN - 38, y + 2, 36, 6, 2, 2, 'F');
      doc.setFontSize(7);
      doc.setTextColor(...WHITE);
      doc.text(school.fit_label.toUpperCase(), PAGE_W - MARGIN - 20, y + 6, { align: 'center' });
      y += 13;

      // Why text
      if (school.why_this_school) {
        need(10);
        doc.setFontSize(7.5);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(...GRAY);
        doc.text(school.why_this_school, MARGIN + 2, y, { maxWidth: CONTENT_W - 4 });
        const lines = doc.splitTextToSize(school.why_this_school, CONTENT_W - 4);
        y += Math.min(lines.length, 3) * 4.5 + 2;
      }

      // Cost breakdown table
      const costRows = [
        ['Annual Tuition', fmt(cb.annual_tuition)],
        ['Pell Grant Applied', `-${fmt(cb.pell_grant_applied)}`],
        ['Tuition Waiver', `-${fmt(cb.annual_tuition - cb.tuition_after_waiver - cb.pell_grant_applied)}`],
        ['ETV Applied', `-${fmt(cb.etv_applied)}`],
        ['Fees + Books + Living', fmt(cb.mandatory_fees + cb.books_supplies + cb.housing_estimate)],
        ['Est. Out-of-Pocket', fmt(cb.estimated_out_of_pocket)],
      ];

      autoTable(doc, {
        startY: y,
        body: costRows,
        theme: 'plain',
        margin: { left: MARGIN + 4, right: MARGIN + 4 },
        bodyStyles: { fontSize: 8, textColor: DARK },
        columnStyles: {
          0: { cellWidth: 80 },
          1: { cellWidth: 40, halign: 'right' },
        },
        didDrawCell: (data) => {
          const raw = data.row.raw as string[];
          const label = raw[0];
          const value = raw[1];
          if (label === 'Est. Out-of-Pocket') {
            data.cell.styles.fontStyle = 'bold';
            data.cell.styles.textColor = TEAL;
            data.cell.styles.fillColor = [235, 248, 242];
          } else if (value.startsWith('-')) {
            data.cell.styles.textColor = GREEN;
          }
        },
      });
      y = (doc as any).lastAutoTable.finalY + 4;

      if (school.foster_support?.program_name) {
        need(8);
        doc.setFontSize(7.5);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...TEAL);
        doc.text(`Foster Support: ${school.foster_support.program_name}`, MARGIN + 4, y);
        y += 5;
      }

      y += 6;
    });
  } else {
    y = notGenerated(doc, y, 'School Matches');
  }

  // ────────────────────────────────────────────────────────────────────────────
  // SECTION 4: ACTION PLAN
  // ────────────────────────────────────────────────────────────────────────────
  need(16);
  y = sectionHeader(doc, y, '4.  ACTION PLAN');

  if (actionPlan) {
    const stepRows = actionPlan.action_plan.map(step => [
      `Step ${step.step_number}`,
      step.title,
      step.specific_action,
      step.deadline ?? '—',
      confidenceLabel(step.confidence),
    ]);

    autoTable(doc, {
      startY: y,
      head: [['#', 'Title', 'Action', 'Deadline', 'Status']],
      body: stepRows,
      theme: 'grid',
      margin: { left: MARGIN, right: MARGIN },
      headStyles: { fillColor: [10, 79, 62], textColor: WHITE, fontStyle: 'bold', fontSize: 7.5 },
      bodyStyles: { fontSize: 7, textColor: DARK },
      columnStyles: {
        0: { cellWidth: 14, halign: 'center', fontStyle: 'bold' },
        1: { cellWidth: 38, fontStyle: 'bold' },
        2: { cellWidth: CONTENT_W - 116 },
        3: { cellWidth: 26 },
        4: { cellWidth: 24 },
      },
      alternateRowStyles: { fillColor: [245, 243, 238] },
    });
    y = (doc as any).lastAutoTable.finalY + 6;

    // Documents needed summary
    const allDocs = actionPlan.action_plan.flatMap(step =>
      step.documents_needed
        .filter(d => d.status === 'need')
        .map(d => [`Step ${step.step_number}`, d.name, d.how_to_get ?? '—'])
    );

    if (allDocs.length > 0) {
      need(16);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...DARK);
      doc.text('Documents You Need to Gather', MARGIN, y);
      y += 5;

      autoTable(doc, {
        startY: y,
        head: [['Step', 'Document', 'How to Get It']],
        body: allDocs,
        theme: 'striped',
        margin: { left: MARGIN, right: MARGIN },
        headStyles: { fillColor: AMBER, textColor: WHITE, fontStyle: 'bold', fontSize: 7.5 },
        bodyStyles: { fontSize: 7, textColor: DARK },
        columnStyles: {
          0: { cellWidth: 16, halign: 'center' },
          1: { cellWidth: 56, fontStyle: 'bold' },
          2: { cellWidth: CONTENT_W - 72 },
        },
        alternateRowStyles: { fillColor: [252, 248, 240] },
      });
      y = (doc as any).lastAutoTable.finalY + 6;
    }
  } else {
    y = notGenerated(doc, y, 'Action Plan');
  }

  // ────────────────────────────────────────────────────────────────────────────
  // SECTION 5: SEMESTER ROADMAP
  // ────────────────────────────────────────────────────────────────────────────
  need(16);
  y = sectionHeader(doc, y, '5.  SEMESTER ROADMAP');

  if (roadmap) {
    const sr = roadmap.semester_roadmap;

    // Overview row
    need(16);
    doc.setFillColor(10, 79, 62);
    doc.roundedRect(MARGIN, y, CONTENT_W, 13, 2, 2, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...WHITE);
    doc.text(sr.based_on_school, MARGIN + 4, y + 6, { maxWidth: CONTENT_W - 8 });
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(180, 230, 215);
    doc.text(
      `Starting ${sr.recommended_start}  |  ${sr.total_semesters_to_degree} semesters to degree`,
      MARGIN + 4, y + 11
    );
    y += 17;

    // All phases as one table
    const phaseRows = sr.phases.flatMap(phase =>
      phase.tasks.map(task => [
        phase.name,
        task.task,
        task.estimated_time ?? '—',
        task.deadline ?? '—',
        task.category ?? '—',
      ])
    );

    if (phaseRows.length > 0) {
      autoTable(doc, {
        startY: y,
        head: [['Phase', 'Task', 'Time', 'Deadline', 'Category']],
        body: phaseRows,
        theme: 'grid',
        margin: { left: MARGIN, right: MARGIN },
        headStyles: { fillColor: TEAL, textColor: WHITE, fontStyle: 'bold', fontSize: 7.5 },
        bodyStyles: { fontSize: 7, textColor: DARK },
        columnStyles: {
          0: { cellWidth: 30, fontStyle: 'bold', textColor: TEAL },
          1: { cellWidth: CONTENT_W - 106 },
          2: { cellWidth: 20 },
          3: { cellWidth: 24 },
          4: { cellWidth: 22 },
        },
        alternateRowStyles: { fillColor: [245, 243, 238] },
        didParseCell: (data) => {
          // Group header rows by phase using rowSpan simulation — color the phase column
          if (data.column.index === 0 && data.section === 'body') {
            const phase = sr.phases.find(p => p.name === data.cell.raw);
            if (phase) {
              const c: [number, number, number] =
                phase.phase_type === 'preparation' ? AMBER :
                phase.phase_type === 'summer' ? [14, 165, 233] :
                phase.phase_type === 'graduation' ? [202, 138, 4] : TEAL;
              data.cell.styles.textColor = c;
            }
          }
        },
      });
      y = (doc as any).lastAutoTable.finalY + 6;
    }

    // Phase cost summary
    const phasesWithCost = sr.phases.filter(p => p.semester_cost_estimate != null);
    if (phasesWithCost.length > 0) {
      need(16);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...DARK);
      doc.text('Cost by Phase', MARGIN, y);
      y += 5;

      const costRows = phasesWithCost.map(p => [
        p.name,
        fmt(p.semester_cost_estimate!),
        p.funding_applied ?? '—',
      ]);

      autoTable(doc, {
        startY: y,
        head: [['Phase', 'Est. Cost', 'Funding Applied']],
        body: costRows,
        theme: 'striped',
        margin: { left: MARGIN, right: MARGIN },
        headStyles: { fillColor: [10, 79, 62], textColor: WHITE, fontStyle: 'bold', fontSize: 7.5 },
        bodyStyles: { fontSize: 7.5, textColor: DARK },
        columnStyles: {
          0: { cellWidth: 50, fontStyle: 'bold' },
          1: { cellWidth: 30, halign: 'right', textColor: TEAL },
          2: { cellWidth: CONTENT_W - 80 },
        },
        alternateRowStyles: { fillColor: [245, 243, 238] },
      });
      y = (doc as any).lastAutoTable.finalY + 6;
    }
  } else {
    y = notGenerated(doc, y, 'Semester Roadmap');
  }

  // Final footer
  addFooter(doc);

  doc.save('path-forward-college-plan.pdf');
}
